# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      entrypoint_script: hash_csv.py
      test_script: unittest_hash_csv.py
      data_file: customer

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      working-directory: src

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      working-directory: ./src

    - name: Pre-script - sample top 5 rows from 
      run: |
        head -5 customer.csv
      working-directory: ./data

    - name: Run ${{env.entrypoint_script}}
      run: |
        python ${{env.entrypoint_script}} --source ../data/customer.csv --config config/config.json
      working-directory: ./src

    - name: Post-script - sample top 5 rows from 
      run: |
        head -5 customer.csv
      working-directory: ./src/output/

    - name: Run ${{env.test_script}} on ${{env.entrypoint_script}}
      run: |
        head -5 ../output/customer-obfuscated.csv
        python ${{env.test_script}}
      working-directory: ./tests